name: Lint

on: [push, pull_request]

jobs:
  black:

    # prevent actions from running on both the push to the PR and PR
    # only run actions on PRs originating from a fork
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Environment
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install black

    - name: Lint
      id: black-check
      shell: bash
      continue-on-error: true
      run: black optking --check -l 120
     
    - name: Fixup
      if: steps.black-check.outcome == 'failure'
      shell: bash
      run: |
        black optking -l 120
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git config --global github.token $ {{ secrets.GITHUB_TOKEN }}
        git add .
        git commit -am "fixup: Format Python code with Black"
        git push

